# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    defaults:
      # for micromamba
      run:
        shell: bash -l {0}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        cdo-version: [null, 1.9.6, 2.0.0]

    name: python ${{ matrix.python-version }} ${{ matrix.cdo-version != null && "with" || "without" }} cdo ${{ matrix.cdo-version }}
    steps:
      - uses: haya14busa/action-cond@v1
        id: nameval
        with:
          cond: ${{ matrix.cdo-version != null }}
          if_true: with cdo ${{ matrix.cdo-version }}
          if_false: without cdo

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags.
      - uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge
          channel-priority: strict
          mamba-version: "*"
          activate-environment: convml_tt
          auto-update-conda: false
          python-version: ${{ matrix.python-version }}

      - name: Set up conda environment
        if: matrix.cdo-version != null
        run: |
          mamba install cdo==${{ matrix.cdo-version }} -c conda-forge

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[test]"
      - name: Test package with pytest
        run: |
          CDO_VERSION=${{ matrix.cdo-version }} python -m pytest
